---

- name: 'Check mandatory variables are defined'
  ansible.builtin.assert:
    that:
      - application_name is defined
      - loki_url is defined
      - expenses_api_endpoint is defined
      - host_port is defined
      - version is defined

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    pull: true
    cleanup: true
    image: "namelivia/{{ application_name }}:{{ version }}"
    memory: "10MB"
    restart_policy: "always"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    exposed_ports:
      - "80"
    published_ports:
      - "0.0.0.0:{{ host_port }}:80"
    networks:
      - name: "pomerium"
    env:
      VUE_APP_API_ENDPOINT: "{{ expenses_api_endpoint }}"
