galaxy_info:
  role_name: movie_quote_mastodon_bot
  namespace: namelivia
  author: Jos√© Ignacio Amelivia Santiago <hello@namelivia.com>
  description: Ansible role I use to install and configure namelivia/movie-quote-mastodon-bot
  license: GPLv2
  min_ansible_version: 2.5.1
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
